# Generated by Django 6.0.6 on 2026-06-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='committee',
            table='api_committee',
        ),
        migrations.AlterModelTable(
            name='committeetype',
            table='api_committeetype',
        ),
        migrations.AlterModelTable(
            name='fiscalyear',
            table='api_fiscalyear',
        ),
        migrations.AlterModelTable(
            name='member',
            table='api_member',
        ),
        migrations.AlterModelTable(
            name='office_model',
            table='api_office_model',
        ),
        migrations.AlterModelTable(
            name='plan',
            table='api_plan',
        ),
        migrations.AlterModelTable(
            name='projects',
            table='api_projects',
        ),
        migrations.AlterModelTable(
            name='ward',
            table='api_ward',
        ),
    ]
