# Generated by Django 6.0.1 on 2026-02-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_apps',
            field=models.ManyToManyField(blank=True, related_name='users', to='user_management.app'),
        ),
    ]
