# Generated by Django 6.0.6 on 2026-06-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_app_name_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
