# Generated by Django 6.0.2 on 2026-02-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darta_chalani', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuchiDarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_Vat_number', models.PositiveIntegerField(max_length=100, unique=True)),
                ('darta_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('darta_date', models.CharField(max_length=20)),
                ('firm_name', models.CharField(max_length=200)),
                ('tax_clearance_FY', models.CharField(max_length=20)),
                ('application_date', models.CharField(max_length=20)),
                ('firm_address', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('firm_darta_number', models.CharField(max_length=100)),
                ('firm_registration_address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('firm_working_sector', models.CharField(max_length=100)),
                ('suchikrit_dastur_bill_number', models.CharField(max_length=100)),
                ('suchikrit_dastur_bill_date', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['darta_number'],
            },
        ),
    ]
