# Generated by Django 6.0.6 on 2026-06-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darta_chalani', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='darta',
            name='letter_catagory',
        ),
        migrations.AlterField(
            model_name='darta',
            name='ref_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
