# Generated by Django 6.0.6 on 2026-06-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darta_chalani', '0002_remove_darta_letter_catagory_alter_darta_ref_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(max_length=200)),
                ('established_date', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('nishan_chap', models.ImageField(blank=True, null=True, upload_to='images/nishan_chap/')),
                ('office_logo', models.ImageField(blank=True, null=True, upload_to='images/office_logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'darta_Chalani_office_model',
            },
        ),
    ]
