# Generated by Django 6.0.2 on 2026-02-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darta_chalani', '0002_suchidarta'),
    ]

    operations = [
        migrations.AddField(
            model_name='suchidarta',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
