# Generated by Django 6.0.2 on 2026-02-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darta_chalani', '0003_suchidarta_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suchidarta',
            name='pan_Vat_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
