# Generated by Django 6.0.6 on 2026-06-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darta_chalani', '0003_office_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=200)),
                ('section_eng_name', models.CharField(max_length=200)),
                ('section_rank_number', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['section_rank_number'],
            },
        ),
    ]
