# Generated by Django 6.0.6 on 2026-07-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darta_chalani', '0004_section_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=200)),
                ('designation_eng_name', models.CharField(max_length=200)),
                ('designation_rank_number', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['designation_rank_number'],
            },
        ),
        migrations.DeleteModel(
            name='Designation',
        ),
    ]
