# Generated by Django 6.0.6 on 2026-07-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darta_chalani', '0005_designation_model_delete_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=200)),
                ('level_eng_name', models.CharField(max_length=200)),
                ('level_rank_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['level_rank_number'],
            },
        ),
    ]
