# Generated by Django 6.0.6 on 2026-07-04 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darta_chalani', '0006_level_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='darta_chalani.designation_model')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='darta_chalani.level_model')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='darta_chalani.section_model')),
            ],
        ),
    ]
