# Generated by Django 6.0.6 on 2026-07-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darta_chalani', '0007_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office_model',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='office_model',
            name='updated_at',
        ),
    ]
