# Generated by Django 6.0.6 on 2026-07-05 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darta_chalani', '0008_remove_office_model_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalani',
            name='receiver_address',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chalani',
            name='sender_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chalani_records', to='darta_chalani.section_model'),
        ),
    ]
